---
abstract: 'main module for biber, a bibtex replacement for users of biblatex'
author:
  - 'François Charette <firmicus@gmx.net>'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: biblatex-biber
provides:
  Biber:
    file: lib/Biber.pm
    version: v0.4.4
  Biber::BibTeX:
    file: lib/Biber/BibTeX.pm
  Biber::BibTeX::PRD:
    file: lib/Biber/BibTeX/PRD.pm
  Biber::BibTeX::Parser:
    file: lib/Biber/BibTeX/Parser.pm
  Biber::Constants:
    file: lib/Biber/Constants.pm
  Biber::Internals:
    file: lib/Biber/Internals.pm
  Biber::Utils:
    file: lib/Biber/Utils.pm
  LaTeX::Decode:
    file: lib/LaTeX/Decode.pm
    version: 0.1
  Parse::RecDescent::Biber::BibTeX::Parser:
    file: lib/Biber/BibTeX/Parser.pm
recommends:
  Readonly::XS: 0
requires:
  Data::Dump: 0
  File::Slurp: 0
  List::AllUtils: 0
  Log::Log4perl: 0
  Readonly: 0
  Regexp::Common: 0
  Text::BibTeX: 0
  XML::LibXML::Simple: 0
resources:
  license: http://dev.perl.org/licenses/
version: v0.4.4
